import type { Metadata } from "next";
import "./globals.css";

import { aladin, kantumruyPro, poppins, srisakdi, openSans } from "../lib/utils/font";
import { ThemeProvider } from 'next-themes'
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${cn(
                    aladin.variable,
                    kantumruyPro.variable,
                    poppins.variable,
                    srisakdi.variable,
                    openSans.variable,
                    "antialiased",
                )}`}
            >
                <ThemeProvider
                    attribute="class"
                    enableSystem
                    defaultTheme="system"
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
