name: Production Automated Deployment
description: Deploys the application to the production server on push to master branch or manually via workflow dispatch

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/sophat.top/v4.sophat.top
            git pull
            npm install
            npm run build
            pm2 restart 1


